export const FETCH_TESTS = 'test/FETCH_TESTS'
export const FETCH_TESTS_SUCCESS = 'test/FETCH_TESTS_SUCCESS'
export const FETCH_TESTS_FAILURE = 'test/FETCH_TESTS_FAILURE'

export const UPDATE_TESTS = 'test/UPDATE_TESTS'
